development:
  adapter: postgresql
  encoding: unicode
  database: arcadian_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: arcadian_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
