development:
  adapter: postgresql
  encoding: unicode
  database: arcadian_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: arcadian_test
  pool: 5
  username: root
  password:
  host: localhost
